from gymnasium.envs.registration import register


register(
    id='quadmaze-large-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='quad',
        maze_env_type='maze',
        maze_type='large',
    )
)
register(
    id=f'quadball-arena-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='quad',
        maze_env_type='ball',
        maze_type='arena',
    )
)
register(
    id=f'quadball-arena-online-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='quad',
        maze_env_type='ball',
        maze_type='arena',
        mode='online',
    )
)
register(
    id='quadball-medium-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='quad',
        maze_env_type='ball',
        maze_type='medium',
    )
)
register(
    id='quadball-medium-online-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='quad',
        maze_env_type='ball',
        maze_type='medium',
        mode='online',
    )
)
register(
    id='humanoidmaze-medium-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='humanoid',
        maze_env_type='maze',
        maze_type='medium',
    )
)
register(
    id='humanoidmaze-large-v0',
    entry_point='envs.locomaze.maze:make_maze_env',
    max_episode_steps=1000,
    kwargs=dict(
        loco_env_type='humanoid',
        maze_env_type='maze',
        maze_type='large',
    )
)
