[project]
name = "ogcrl"
version = "0.0.0"
requires-python = ">= 3.10"

[project.optional-dependencies]
dev = [
    "ruff",
]

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.format]
quote-style = "single"
