from gymnasium.envs.registration import register

register(
    id='cube-online-v0',
    entry_point='envs.robomanip.robomanip:RoboManipEnv',
    max_episode_steps=75,
    kwargs=dict(
        env_type='cube_single',
        mode='online',
        terminate_at_goal=False,
    ),
)

register(
    id='cube-single-v0',
    entry_point='envs.robomanip.robomanip:RoboManipEnv',
    max_episode_steps=200,
    kwargs=dict(
        env_type='cube_single',
    ),
)
register(
    id='cube-double-v0',
    entry_point='envs.robomanip.robomanip:RoboManipEnv',
    max_episode_steps=500,
    kwargs=dict(
        env_type='cube_double',
    ),
)
register(
    id='cube-triple-v0',
    entry_point='envs.robomanip.robomanip:RoboManipEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_triple',
    ),
)
register(
    id='cube-quadruple-v0',
    entry_point='envs.robomanip.robomanip:RoboManipEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_quadruple',
    ),
)
