from gymnasium.envs.registration import register

visual_dict = dict(
    ob_type='pixels',
    width=64,
    height=64,
    visualize_info=False,
)

register(
    id='cube-single-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=200,
    kwargs=dict(
        env_type='cube_single',
    ),
)
register(
    id='visual-cube-single-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=200,
    kwargs=dict(
        env_type='cube_single',
        **visual_dict,
    ),
)
register(
    id='cube-double-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=500,
    kwargs=dict(
        env_type='cube_double',
    ),
)
register(
    id='visual-cube-double-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=500,
    kwargs=dict(
        env_type='cube_double',
        **visual_dict,
    ),
)
register(
    id='cube-triple-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_triple',
    ),
)
register(
    id='visual-cube-triple-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_triple',
        **visual_dict,
    ),
)
register(
    id='cube-quadruple-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_quadruple',
    ),
)
register(
    id='visual-cube-quadruple-v0',
    entry_point='envs.robomanip.cube:CubeEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='cube_quadruple',
        **visual_dict,
    ),
)

register(
    id='scene-v0',
    entry_point='envs.robomanip.scene:SceneEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='scene',
    ),
)
register(
    id='visual-scene-v0',
    entry_point='envs.robomanip.scene:SceneEnv',
    max_episode_steps=1000,
    kwargs=dict(
        env_type='scene',
        **visual_dict,
    ),
)
